### ISSUE TITLE
Background Execution of sudo systemctl reload-or-restart or restart gives a false impression

### ISSUE THREAD

**Issue by radio24** [nyxnor/onionservice#1]
https://github.com/nyxnor/onionservice/blob/5a4f4991fdc6fa8f74e7120a9c4d9cf51cbe7940/.onionrc#L185

**Issue**
Restart or reload-or-restart tor in the background and giving a "Reloaded tor successfully!" after 2 seconds could be misleading because if the restart or to reload-or-restart process gets stuck in the background, the success message is shown anyway after 2 seconds.

**Describe the solution you'd like**
In my opinion, it would be better to inform the user that tor is restarting or doing the reload-or-restart that it would take a moment with a solution to what he/she has to do if a restart or reload-or-restart process gets stuck.

**Additional remarks**
Pull request may follow

**Comment by nyxnor** [comment]
First, I introduced a bug on `set_owner_permission` that you might have been experiencing due to this commit https://github.com/nyxnor/onionservice/commit/12b27b3d60fc49599b34c5a8182e5595e05dcd10
` sudo chmod -R 644 "${TORRC_ROOT}"` is wrong, it should not set 644 to the folder, just to the $TORRC.

Second, I wished bugs wouldn't happen and it would never get stuck, but it does get stuck if the inserted information on the torrc is wrong or the permissions are wrong.

The `&` operand was being used to avoid being stuck but it does not help to solve it, right.

In my experience, restart has never stuck, just reload.
Information about what to do if it gets stuck will be added to the reload option.

PR, already reviewed, I just need to correct the `set_owner_permission` inside the `.onionrc` first.
